"""float_to_numeric_precision

Revision ID: 4291113afde6
Revises: c3a5e8d30493
Create Date: 2026-02-11 20:44:44.067285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4291113afde6'
down_revision = 'c3a5e8d30493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('threshold_price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=False)

    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.alter_column('open',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=True)
        batch_op.alter_column('close',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.alter_column('amount_per_share',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=6),
               existing_nullable=False)

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.alter_column('total_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_invested',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_pnl',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_pnl_pct',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=False)
        batch_op.alter_column('price_per_share',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=False)
        batch_op.alter_column('fees',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=16, scale=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('fees',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('price_per_share',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.alter_column('total_pnl_pct',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_pnl',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_invested',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('total_value',
               existing_type=sa.Numeric(precision=16, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('dividends', schema=None) as batch_op:
        batch_op.alter_column('amount_per_share',
               existing_type=sa.Numeric(precision=16, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=False)

    with op.batch_alter_table('daily_prices', schema=None) as batch_op:
        batch_op.alter_column('close',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('low',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('high',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('open',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('threshold_price',
               existing_type=sa.Numeric(precision=16, scale=4),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
