"""add_live_quotes_table

Revision ID: be69bcd45f08
Revises: 4291113afde6
Create Date: 2026-03-08 18:47:03.009271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be69bcd45f08'
down_revision = '4291113afde6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('change', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('market_state', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_quotes_ticker_id'), ['ticker_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('live_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_quotes_ticker_id'))

    op.drop_table('live_quotes')
    # ### end Alembic commands ###
